version: 2
updates:
  - package-ecosystem: "npm" # See documentation for possible values
    directory: "/CB-Frontend" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "gradle"
    directory: "/CB-Backend"
    schedule:
      interval: "weekly"
